Search.appendIndex(
    [
                {
            "fqsen": "\\expectedKastelaVersion",
            "name": "expectedKastelaVersion",
            "summary": "",
            "url": "namespaces/default.html#constant_expectedKastelaVersion"
        },                {
            "fqsen": "\\protectionPath",
            "name": "protectionPath",
            "summary": "",
            "url": "namespaces/default.html#constant_protectionPath"
        },                {
            "fqsen": "\\vaultPath",
            "name": "vaultPath",
            "summary": "",
            "url": "namespaces/default.html#constant_vaultPath"
        },                {
            "fqsen": "\\Kastela\\Client",
            "name": "Client",
            "summary": "Create\u0020a\u0020new\u0020Kastela\u0020Client\u0020instance\u0020for\u0020communicating\u0020with\u0020the\u0020server.",
            "url": "classes/Kastela-Client.html"
        },                {
            "fqsen": "\\Kastela\\Client\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Kastela-Client.html#method___construct"
        },                {
            "fqsen": "\\Kastela\\Client\u003A\u003Aprotection_seal\u0028\u0029",
            "name": "protection_seal",
            "summary": "Encrypt\u0020data\u0020protection\u0020by\u0020protection\u0020data\u0020ids,\u0020which\u0020can\u0020be\u0020used\u0020after\u0020storing\u0020data\u0020or\u0020updating\u0020data.",
            "url": "classes/Kastela-Client.html#method_protection_seal"
        },                {
            "fqsen": "\\Kastela\\Client\u003A\u003Aprotection_open\u0028\u0029",
            "name": "protection_open",
            "summary": "Decrypt\u0020data\u0020protection\u0020by\u0020protection\u0020data\u0020ids.",
            "url": "classes/Kastela-Client.html#method_protection_open"
        },                {
            "fqsen": "\\Kastela\\Client\u003A\u003Avault_store\u0028\u0029",
            "name": "vault_store",
            "summary": "Store\u0020batch\u0020vault\u0020data\u0020on\u0020the\u0020server.",
            "url": "classes/Kastela-Client.html#method_vault_store"
        },                {
            "fqsen": "\\Kastela\\Client\u003A\u003Avault_fetch\u0028\u0029",
            "name": "vault_fetch",
            "summary": "Search\u0020vault\u0020data\u0020by\u0020indexed\u0020column.",
            "url": "classes/Kastela-Client.html#method_vault_fetch"
        },                {
            "fqsen": "\\Kastela\\Client\u003A\u003Avault_get\u0028\u0029",
            "name": "vault_get",
            "summary": "Get\u0020batch\u0020vault\u0020data\u0020by\u0020vault\u0020token\u0020ids.",
            "url": "classes/Kastela-Client.html#method_vault_get"
        },                {
            "fqsen": "\\Kastela\\Client\u003A\u003Avault_update\u0028\u0029",
            "name": "vault_update",
            "summary": "Update\u0020vault\u0020data\u0020by\u0020vault\u0020token.",
            "url": "classes/Kastela-Client.html#method_vault_update"
        },                {
            "fqsen": "\\Kastela\\Client\u003A\u003Avault_delete\u0028\u0029",
            "name": "vault_delete",
            "summary": "Remove\u0020vault\u0020data\u0020by\u0020vault\u0020token.",
            "url": "classes/Kastela-Client.html#method_vault_delete"
        },                {
            "fqsen": "\\Kastela\\Client\u003A\u003A\u0024kastelaUrl",
            "name": "kastelaUrl",
            "summary": "",
            "url": "classes/Kastela-Client.html#property_kastelaUrl"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Kastela",
            "name": "Kastela",
            "summary": "",
            "url": "namespaces/kastela.html"
        }            ]
);
